Лаба на сдачу №2
avalon-dev-j110/laboratornaya-rabota-no2-Lena-Helen17 pull request #1
Opened 2020-04-06 05:56 UTC by Lena-Helen17

На проверку

2020-04-08 21:28 UTC, KolosovKD requested changes

2020-04-08 21:28 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/Application.java
> +     float max = shapes[0].getArea();
метод публичный, значит он доступен всем (вызов метода не под вашим контролем, его могут использовать кто угодно за пределами ваших классов). Стои добавить первой строкой проверку - а есть ли вообще в массиве хоть один элемент. Ведь если метод вызовут с массивом вообще без элементов, будет выброшено исключение.

2020-04-08 21:28 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/shapes/Circle.java
> +public class Circle extends PointClass implements Ellipse {
Класс Circle не является наследником класса PointClass. В геометрическом смысле, круг состоит из точек.
Здесь между ними не наследование, а скорее агрегация. Класс Circle просто имеет поле типа Point - центр окружности. Возможно еще какие-то поля, необходимые для нашей задачи. Например, радиус.

2020-04-08 21:28 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/shapes/Point.java
> +    float getX(float x1, float x2) ;
методы-геттеры должны возвращать значение, у них, обычно, нет параметров.

2020-04-08 21:28 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/shapes/Point.java
> +    float getY(float y1, float y2);
методы-геттеры должны возвращать значение, у них, обычно, нет параметров.

2020-04-08 21:28 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/shapes/PointClass.java
> +    private float tochka2Y;
Класс _*точка*_ должен моделировать точку. В нашем случае - это точка на плоскости. То есть у нее есть всего две характеристики - это две ее координаты (абсцисса и ордината).

2020-04-08 21:28 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/shapes/Triangle.java
> +public class Triangle extends PointClass implements Polygon{
треугольник не является расширением точки в нашем случае.

2020-04-12 16:39 UTC, konivex approved these changes
Зачтено.

2020-04-18 13:44 UTC, merged